### ISSUE TITLE
How to change map behavior

### ISSUE THREAD

**Issue by oleg0032** [ddubrava/angular-yandex-maps#10]
```
<angular-yandex-map [center]="[55.751952, 37.600739]" [zoom]="12">
    <angular-yandex-placemark [geometry]="[55.751952, 37.600739]"></angular-yandex-placemark>
</angular-yandex-map>
```

Example: https://tech.yandex.ru/maps/jsbox/2.1/behaviors

**Comment by ddubrava** [comment]
Привет, любой компонент возвращает свой instance в ивентах, в этом случае нужна карта.
Описание ивентов + что они возвращают можно посмотреть [тут](https://ddubrava.github.io/angular-yandex-maps-docs/docs/map)

https://stackblitz.com/edit/map-behavior
