### ISSUE TITLE
Нужно получение адреса маркера который поставил пользователь через поиск

### ISSUE THREAD

**Issue by GGnet123** [ddubrava/angular-yandex-maps#14]
Здравствуй, можешь пожалуйста подсказать каким образом можно получить адрес который указал пользователь? Ну или как написать event на новый маркер на карте (Когда пользователь пишет нужный адрес появляется маркер).Буду очень благодарен

**Comment by ddubrava** [comment]
Привет, куда пользователь пишет новый адрес?

**Comment by GGnet123** [comment]
В строку поиска. У меня есть страница с яндекс картой и мне нужно получить какой адрес выбрал пользователь. К примеру он начал писать в поиск улица Пушкина, 77 и в появившемся списке предложений адресов он выбрал нужный ему. После он жмет на кнопку продолжить и в этот момент я хочу получить его адрес

**Comment by ddubrava** [comment]
https://stackblitz.com/edit/get-search-request
