### ISSUE TITLE
How to manage controls?

### ISSUE THREAD

**Issue by dmitriytretyakov** [ddubrava/angular-yandex-maps#15]
Hi, thanks for yur solution. How can i hide search input or another controls?

**Comment by ddubrava** [comment]
Привет, у [https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/Map-docpage/#Map__param-state.controls](*Map*) есть state.controls, он принимает массив контролов, в документации Яндекс.Карт все подробно описано.

`<angular-yandex-map
  [center]="[55.751952, 37.600739]"
  [zoom]="8"
  [state]="{ controls: [] }" // <-- Вот state.controls из документации
>`

**Comment by dmitriytretyakov** [comment]
Спасибо )
