### ISSUE TITLE
Есть ли возможность работы с SuggestView

### ISSUE THREAD

**Issue by OdvansGame** [ddubrava/angular-yandex-maps#17]
Использую последнюю версию модуля. Необходимо реализовать обычный SuggestView, который в проекте без Angular реализуется за 2 минуты. Собственно вопрос, есть ли возможность используя ваш модуль организовать SuggestView?

**Comment by ddubrava** [comment]
Привет, из модуля можно получить ymaps, а с помощью него сделать все что угодно. Так как карат не нужна, то можно использовать [onlyInstance](https://ddubrava.github.io/angular-yandex-maps-docs/docs/map) input.

[Пример работы с ymaps без создания карты](https://stackblitz.com/edit/only-ymaps-instance)

**Comment by ddubrava** [comment]
[Sugget-view](https://stackblitz.com/edit/suggest-view)
