### ISSUE TITLE
Получаю Invalid Api Key даже без его указания

### ISSUE THREAD

**Issue by OdvansGame** [ddubrava/angular-yandex-maps#18]
Module:
`import {AngularYandexMapsModule} from 'angular8-yandex-maps';`
`import:[AngularYandexMapsModule]`

Component.ts:
    
    constructor() {}
    public onLoad(event: ILoadEvent) {
    const ymaps = event.ymaps;

    ymaps.geocode('Moscow')
      .then((res) => {
        console.log(
          res.geoObjects.get(0).properties.get('metaDataProperty')
        );
      });
     }

Component.html:
`        <div class="map">
          <angular-yandex-map [onlyInstance]="true" (load)="onLoad($event)"></angular-yandex-map>
        </div>`

Получаю: Invalid Api Key, соответсвенно ничего не выводится

**Comment by ddubrava** [comment]
Invalid API key это варнинг из API Яндекс.Карт, а не модуля. Чтобы геокодер в данном [примере](https://stackblitz.com/edit/only-ymaps-instance) работал надо передать свой ключ. [Получить ключ можно так](https://developer.tech.yandex.ru/services/)

**Comment by OdvansGame** [comment]
Я уже несколько дней бьюсь над проблемой с подключением SuggestView. Если вас не затруднит, могли бы вы написать кусочек кода, который исправил бы мою проблему. Понимаю, что не по теме, но перерыл уже весь интернет. Заранее спасибо
