### ISSUE TITLE
Не удается получить адресс из поля

### ISSUE THREAD

**Issue by OdvansGame** [ddubrava/angular-yandex-maps#19]
Получил instance из angular-yandex-map и добавил SuggestView. Все прекрастно работает до того момента пока не попытаешь из этого поля взять адресс. Вместо полного адресса я получаю только то, что я написал сам, а не полностью весь адресс.

Создаю SuggestView

    public onLoad(event: ILoadEvent) {
       const ymaps = event.ymaps;

       ymaps.load().then(res => {
         var suggest = new res.SuggestView('training_address');
       }).catch(error => console.log(error));
    }

HTML: 
```
        <div class="map">
          <angular-yandex-map [onlyInstance]="true" (load)="onLoad($event)"></angular-yandex-map>
        </div>
        <input name="address" [(ngModel)]="address" type="text" id="training_address"
                                          class="form-control"
                                          nbInput fullWidth status="basic"
                                          placeholder="Kirjutage treeningute addressi...">
```
В чем может быть проблема?

**Comment by ddubrava** [comment]
Привет, результат выбора из SuggestView не проставляется в value. Для получения результата можно добавить листенер на ['select'](https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/SuggestView-docpage/#event_detail__event_detail/event-select) событие.

[stackblitz](https://stackblitz.com/edit/suggest-view)
