### ISSUE TITLE
конфигурация не применяется, когда карта подключается не в главном модуле приложения

### ISSUE THREAD

**Issue by sa-va** [ddubrava/angular-yandex-maps#21]
Описание:
конфигурация не применяется, когда карта подключается не в главном модуле приложения

Воспроизведение:
карта находится в отдельном модуле (map.module.ts), подключена вот так:
AngularYandexMapsModule.forRoot({ apiKey: 'my-key', lang: 'ru_RU'})
После запуска приложения указанная конфигурация не применяется (ключ становится null и локализация en_RU), хотя карта работает.

Ожидание:
angular-yandex-maps подключен только в модуле map.module.ts, применяется указанная конфигурация.

Версия: 1.14.0

Дополнительно:
конфигурация срабатывает только если прописать в главном модуле приложения (app.module.ts)
AngularYandexMapsModule.forRoot({ apiKey: 'my-key', lang: 'ru_RU'})

**Comment by ddubrava** [comment]
Привет, правильно понял проблему - https://stackblitz.com/edit/multiple-modules?

**Comment by sa-va** [comment]
так, но еще модуль карты в lazy-loading

const routes: Routes = [
  {
    path: 'map',
    loadChildren: () => import('./map/map.module').then(m => m.MapModule)
  }
];

**Comment by ddubrava** [comment]
Добавил lazy-loading.

https://stackblitz.com/edit/multiple-modules

**Comment by sa-va** [comment]
в AppModule в блоке imports исключить MapModule
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule
  ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }

**Comment by ddubrava** [comment]
Какая версия Angular в проекте?

Я сделал на 6 и 9, вроде работает. Но я не понимаю, почему, например, не работает в предыдущих примерах.

https://stackblitz.com/edit/lazy-loading-map

**Comment by sa-va** [comment]
в проекте angular 9. 

я открыла https://stackblitz.com/edit/lazy-loading-map, в инструментах разработчика / сеть карта загружается как:
https://api-maps.yandex.ru/2.1/?apiKey=null&lang=en_RU

карта работает, но конфигурация как будто не применяется

**Comment by ddubrava** [comment]
Да, конфиг не прокидывается до сервиса. 

forRoot видимо не реализовать для lazy modules - https://stackoverflow.com/questions/48601849/angular-lazy-load-does-not-work-when-invoking-forroot

Я попробую что-то сделать с этим, но пока только вариант импортить не в lazy
