### ISSUE TITLE
❓ Incorrect searching in RU

### ISSUE THREAD

**Issue by i-gera** [ddubrava/angular-yandex-maps#229]
### Description

the drop-down list offers options that do not correspond to the entered value in Cyrillic. but when i'm searching in latin everything's fine:
![image](https://github.com/ddubrava/angular8-yandex-maps/assets/24408692/1846aae0-435e-43e3-86ce-7cd5cc25c266)

when i'm searching in eng everything's fine:
![image](https://github.com/ddubrava/angular8-yandex-maps/assets/24408692/f4ed5995-4751-42ad-9518-1ce64f01580a)

AngularYandexMapsModule.forRoot({
      apikey: 'my api key from yandex',
      lang: 'ru_RU',
    })

**Comment by ddubrava** [comment]
Hi! Could you create a repro? Actually, this library doesn't do anything with geocoding. You use a yandex dropdown component, it makes all the requests out of the box. If you create a small repro, I can try to help you

**Comment by i-gera** [comment]
> Hi! Could you create a repro? Actually, this library doesn't do anything with geocoding. You use a yandex dropdown component, it makes all the requests out of the box. If you create a small repro, I can try to help you

Suggest is not available. See https://yandex.com/dev/jsapi-v2-1/doc/en/v2-1/ref/reference/suggest
![image](https://github.com/ddubrava/angular8-yandex-maps/assets/24408692/f7e91ca2-428d-4571-a162-35fbbf86a421)

https://ru.stackoverflow.com/questions/1543130/%d0%9f%d0%b5%d1%80%d0%b5%d1%81%d1%82%d0%b0%d0%bb%d0%b0-%d1%80%d0%b0%d0%b1%d0%be%d1%82%d0%b0%d1%82%d1%8c-%d1%81%d1%82%d1%80%d0%be%d0%ba%d0%b0-%d0%bf%d0%be%d0%b8%d1%81%d0%ba%d0%b0-suggestview-%d1%85%d0%b5%d0%bb%d0%bf

It is written everywhere that now we need to get a special suggest_apikey. Where can I add it after receiving so that it is sent in the request parameters? 
![image](https://github.com/ddubrava/angular8-yandex-maps/assets/24408692/3664ecc1-f511-4ce3-8558-10a27637dde4)
