### ISSUE TITLE
Поменять ссылку карты на платную версию api

### ISSUE THREAD

**Issue by sa-va** [ddubrava/angular-yandex-maps#24]
Добрый день, как поменять ссылку карты на платную версию api?

https://enterprise.api-maps.yandex.ru/2.1?apikey=ваш API-ключ&lang=<идентификатор языка>&<дополнительные параметры>

**Comment by ddubrava** [comment]
Обновитесь до 1.14.5.

Добавил `{ enterprise?: boolean }` в [IConfig](https://github.com/ddubrava/angular-yandex-maps/blob/develop/projects/angular8-yandex-maps/src/lib/models/models.ts#L7).


```
import { AngularYandexMapsModule, IConfig } from 'angular8-yandex-maps';

const mapConfig: IConfig = {
  apikey: '658f67a2-fd77-42e9-b99e-2bd48c4ccad4',
  lang: 'en_US',
  enterprise: true,
};

@NgModule({
  imports: [AngularYandexMapsModule.forRoot(mapConfig)]
})
export class AppModule { }
```

**Comment by sa-va** [comment]
спасибо, получилось!
