### ISSUE TITLE
❓ - Custom markers are not displayed

### ISSUE THREAD

**Issue by 14837-eng** [ddubrava/angular-yandex-maps#245]
### Description

I use the code from the documentation - the markers are not displayed, I change the markers to the default ones and everything works. What should I do to make the markers created by the programmer work?

### Library name

- [ ] angular8-yandex-maps
- [X] angular-yandex-maps-v3

**Comment by ddubrava** [comment]
Hi! The library is nothing more than a midleware between Angular and the Yandex.Maps API. So in your case you can check these examples (select react.html, components are almost the same)

- https://yandex.ru/dev/jsapi30/doc/en/examples/cases/marker-custom-icon
- https://yandex.ru/dev/jsapi30/doc/en/examples/cases/create-default-marker

The difference is that [YMapMarker](https://yandex.ru/dev/jsapi30/doc/en/ref/#class-ymapmarker) 

> Allows you to insert your own DOM implementation of the marker.

While [YMapDefaultMarker](https://yandex.ru/dev/jsapi30/doc/en/ref/packages/markers/#class-ymapdefaultmarker) has a layout out of the box.

So all you need to do is whether use YMapDefaultMarker or use YMapMarker and pass your custom HTML

**Comment by 14837-eng** [comment]
An image was transferred inside the tag. According to the [documentation](https://ddubrava.github.io/angular-yandex-maps/#/v3/components/YMapMarkerDirective). There are no errors in the console.
But there was no result either

**Comment by 14837-eng** [comment]
Sorry for the disinfo. The problem was not in your library, but in a tailwind conflict between Yandex api.
