### ISSUE TITLE
❓ - Dark Theme

### ISSUE THREAD

**Issue by grinderek** [ddubrava/angular-yandex-maps#246]
### Description

Is there any way to make a dark map theme for yandex api v2?

### Library name

- [X] angular8-yandex-maps
- [ ] angular-yandex-maps-v3

**Comment by ddubrava** [comment]
Hi! I'm not sure if it's possible, to be honest. In production, they use the 3rd version, so a dark theme is available. Regarding the 2nd version, I couldn't find anything in the API. You can ask support; maybe there is a parameter for this somewhere
