### ISSUE TITLE
❓ - Zoom duraction

### ISSUE THREAD

**Issue by 14837-eng** [ddubrava/angular-yandex-maps#247]
### Description

How can I adjust the zoom on custom buttons so that it is smooth?

I can do this in the react library, but how can I do it in the current library? Updating the counter does not give smoothness :(

![image](https://github.com/user-attachments/assets/dba37912-935d-4c2a-beca-d5f4628e3922)

### Library name

- [ ] angular8-yandex-maps
- [X] angular-yandex-maps-v3

**Comment by ddubrava** [comment]
Hi! Have you tried this component https://ddubrava.github.io/angular-yandex-maps/#/v3/components/YMapZoomControlDirective?id=ymapzoomcontroldirective?

**Comment by ddubrava** [comment]
You need to pass a `duration` property to `props.location`.

```
<div class="container">
  <y-map
    (ready)="onMapReady($event)"
    [props]="{
      location: {
        center: [-0.127696, 51.507351],
        zoom,
        duration: 200,
      },
    }"
  >
    <y-map-default-scheme-layer />
  </y-map>
</div>

<button (click)="onZoom(1)">Zoom In</button>
<button (click)="onZoom(-1)">Zoom Out</button>
```

**Comment by 14837-eng** [comment]
thx
