### ISSUE TITLE
❓ - How can I interact with LoadingObjectManager

### ISSUE THREAD

**Issue by Rouvas** [ddubrava/angular-yandex-maps#257]
### Description

Приветствую! Разбираясь с возможностью подгрузки объектов, в документации (примерах) предложен ObjectManager (https://ddubrava.github.io/angular-yandex-maps/#/v2/components/YaObjectManagerDirective). Подскажите, возможно ли как-то использовать LoadingObjectManager?

Заранее благодарю за ответ.
p.s. пробовал дергать ymaps из ready, но пока не удачно :(

### Library name

- [X] angular8-yandex-maps
- [ ] angular-yandex-maps-v3

**Comment by ddubrava** [comment]
Привет, LoadingObjectManager поддержу через пару недель. Касаемо временного решения получить его можно так

```html
<ya-map [center]="[55.751952, 37.600739]" (ready)="onReady($event)"></ya-map>
```

```ts
onReady(event: YaReadyEvent<ymaps.Map>) {
  // нужен кастинг потому что в типах нет этого класса
  console.log((event.ymaps as any).LoadingObjectManager);
}
```

**Comment by ddubrava** [comment]
Добавил. Будет в `18.2.0`
