### ISSUE TITLE
❓ - clusters

### ISSUE THREAD

**Issue by 14837-eng** [ddubrava/angular-yandex-maps#258]
### Description

Is there any way to display clusters in the template? Is there a component or an example implementation?

### Library name

- [ ] angular8-yandex-maps
- [X] angular-yandex-maps-v3

**Comment by ddubrava** [comment]
Hi! It's not implemented right now. You can use a `ready` event on a map, then access `ymaps` and use a cluster without a component - https://yandex.ru/dev/jsapi30/doc/ru/ref/packages/clusterer/. I'll implement a component in a few weeks

**Comment by ddubrava** [comment]
Reopened, so I won't forget about the component

**Comment by ddubrava** [comment]
Available in `18.3.0`.

Here is the example - https://github.com/ddubrava/angular-yandex-maps/blob/main/apps/angular-yandex-maps-v3-demo/src/app/app.component.html#L197
