### ISSUE TITLE
Карта не работает в firefox 45 версии

### ISSUE THREAD

**Issue by moskinov** [ddubrava/angular-yandex-maps#26]
Здравствуйте. На сколько я помню версия 1.12.0 работала firefox 45
После перехода на 1.14.5, карта перестала отображаться, ошибок никаких нет, просто пустой компонент angular-yandex-map
Версия карты подключается 2.1
Судя по документации https://tech.yandex.ru/maps/jsapi/doc/2.1/dg/concepts/load-docpage/ для старых браузеров IE8, IE9 и IE10 автоматически должна подгружаться другая версия 2.1.oldie.1
Возможно то же касается и firefox 45

**Comment by ddubrava** [comment]
Добрый день, с версии 1.12.0 многое изменилось, включая обратную совместимость (в этом моя ошибка, что это минор , а не мажор был). Скорее всего, проблема в том, что в [1.13.0](https://github.com/ddubrava/angular-yandex-maps/blob/develop/CHANGELOG.md#1130---2020-05-21) изменился метод forRoot.

**Comment by moskinov** [comment]
модуль карты импортируется в корневом модуле AppModule
метод forRoot принимает небольшой конфиг: 
const mapConfig: IConfig = {
    apikey: '?????',
    lang: 'ru_RU',
    enterprise: true
};

AngularYandexMapsModule.forRoot(mapConfig)

**Comment by moskinov** [comment]
даже по вашей ссылке с примерами использования https://ddubrava.github.io/angular-yandex-maps-docs/docs/map
в firefox 45 блок с картой "Preview" пустой

**Comment by moskinov** [comment]
![image](https://user-images.githubusercontent.com/13706859/88383539-6543be80-cdb3-11ea-89b3-48cac7fddca1.png)

**Comment by moskinov** [comment]
скрипты загружены, консоль молчит ошибок нет
![image](https://user-images.githubusercontent.com/13706859/88383886-10ed0e80-cdb4-11ea-9a18-de72021c27e3.png)

**Comment by ddubrava** [comment]
Oldie пофиксило проблему, сейчас выпущу релиз

**Comment by ddubrava** [comment]
Добавил version в IConfig, [1.15.0](https://github.com/ddubrava/angular-yandex-maps/releases/tag/v1.15.0).

```
const mapConfig: IConfig = {
  apikey: '?????',
  lang: 'ru_RU',
  enterprise: true,
  version: '2.1.oldie',
};
```

**Comment by moskinov** [comment]
Спасибо, в гите вижу, а на npm пакет когда обновится? https://www.npmjs.com/package/angular8-yandex-maps

**Comment by ddubrava** [comment]
Пакет тоже обновил

**Comment by moskinov** [comment]
Все получилось, спасибо! Вопрос закрыт
