### ISSUE TITLE
🐞 - TypeError: this.EC9_map.projection.fromWorldCoordinates is not a function

### ISSUE THREAD

**Issue by 14837-eng** [ddubrava/angular-yandex-maps#263]
### Description

I just didn't touch anything and I got this error. When changing the zoom, an error with the projection began to appear

full error: 
![image](https://github.com/user-attachments/assets/77b097ba-e6bb-4b0f-8b28-bac773554657)

my code: 

`  setZoom(zoom: number, mapSettings: YMapProps) {
    this.mapSettings.set({
      ...mapSettings,
      location: {
        ...mapSettings,
        duration: this.DEFAULT_DURACTION,
        center: this.mapCenter,
        zoom,
      },
    });
  }`

### Angular version

16.0.1

### Library name

- [ ] angular8-yandex-maps
- [X] angular-yandex-maps-v3

### Library version

18.2.0

**Comment by ddubrava** [comment]
Hi! Could you create a repro?
