### ISSUE TITLE
Null Inject Error

### ISSUE THREAD

**Issue by fermanquliyev** [ddubrava/angular-yandex-maps#3]
I get this errors:
StaticInjectorError(RootModule)[API_KEY]: 
  StaticInjectorError(Platform: core)[API_KEY]: 
    NullInjectorError: No provider for API_KEY!

Cannot read property 'initScript' of undefined
    at YandexMapComponent.push../node_modules/angular8-yandex-maps/fesm5/angular8-yandex-maps.js.YandexMapComponent.ngOnInit (angular8-yandex-maps.js:472)

My module import:
AngularYandexMapsModule.forRoot('my-key-xxx'),

**Comment by ddubrava** [comment]
Hello!

Can you publish your code in StackBlitz, please? If you are using import with .forRoot(), everything should be working. These errors occur when you are not using .forRoot(). 

I also made .forRoot() optional - https://github.com/ddubrava/angular-yandex-maps/commit/75b871ece9e6e9edb3ad4ebe08915f2bac4220ce.

**Comment by ddubrava** [comment]
Close the issue due to inactivity
