### ISSUE TITLE
No icon caption?

### ISSUE THREAD

**Issue by Alex2033** [ddubrava/angular-yandex-maps#4]
In the examples there are hintContent and balloonContent, but I didn't find iconCaption, which will be displayed initially independently on hover or click as hintContent and balloonContent. Does this option exist in this project?

**Comment by ddubrava** [comment]
Hey!

You can use any properties, options from Yandex.Maps API (in your case [Placemark](https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/Placemark-docpage/)). HintContent and balloonContent are just examples, you can use what you want.

Example with iconCaption:
https://stackblitz.com/edit/placemark-pie-chart

**Comment by Alex2033** [comment]
okay, thanks!
