### ISSUE TITLE
Кастомный iconContent

### ISSUE THREAD

**Issue by Alex2033** [ddubrava/angular-yandex-maps#5]
Подскажите пожалуйста как в вашей библиотеке можно сделать свой кастомный iconContent?
Если обратиться к оф. документации мы видим следующее https://tech.yandex.ru/maps/jsbox/2.1/?from=techmapsmain

Где iconContentLayout: MyIconContentLayout, а MyIconContentLayout в свою очередь создается следующим образом (более наглядно по ссылке):

MyIconContentLayout = ymaps.templateLayoutFactory.createClass(
    '<div style="color: #FFFFFF; font-weight: bold;">$[properties.iconContent]</div>'
),

Подскажите как в данной библиотеке это реализовать?

**Comment by ddubrava** [comment]
Добрый день!

Пример как в документации Яндекс.Карт - https://stackblitz.com/edit/custom-placemark-2

В библиотеке доступ к ymaps можно получить только после создания карты/панорамы, чтобы получить ymaps и инстанс нужной метки используем [placemark load output](https://ddubrava.github.io/angular-yandex-maps-docs/docs/placemark). Для создания MyIconContentLayout класса используем - ymaps, а для добавления iconContentLayout опции - instance. 

Еще один пример кастомной метки из документации библиотеки - https://stackblitz.com/edit/custom-placemark
