### ISSUE TITLE
Можно ли использовать Адрес вместо latitude и longitude? 

### ISSUE THREAD

**Issue by Denis-Evseev** [ddubrava/angular-yandex-maps#7]
Спасибо Даниил за библиотеку! 
Очень странно, что Яндекс не реализовал этого сам... 

Не подскажешь можно ли использовать адрес для установки маркера вместо latitude и longitude?

**Comment by ddubrava** [comment]
Привет!

Судя по документации center принимает только Number[], поэтому надо получить координаты адреса. Сделать это можно через [geocode](https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/geocode-docpage/). 

Вот решение - https://stackblitz.com/edit/geocoder

У Яндекса нет Angular разработчиков и ресурсов на разработки библиотек 🙁

P.S. Нет пожеланий как лучше назвать компоненты angular-yandex-*? Мне кажется, что названия слишком громоздкие и можно упростить их до ng-ymaps, например.

**Comment by Denis-Evseev** [comment]
ng-ymap?

**Comment by Denis-Evseev** [comment]
@ddubrava пример перестал работать:
https://stackblitz.com/edit/only-ymaps-instance?file=src%2Fapp%2Fapp.component.html

**Comment by Denis-Evseev** [comment]
Не знаешь как можно получить координаты и использовать и в центрирование и при добавлении точки? 
Спасибо!

**Comment by ddubrava** [comment]
Напиши мне, пожалуйста, в [https://teleg.run/ddubrava](telegram)
