### ISSUE TITLE
bootstrap-4 портит отображение карты

### ISSUE THREAD

**Issue by frodoom** [ddubrava/angular-yandex-maps#8]
Здравствуете. 
Я новичок в angular и недавно начал использовать данное решение в своем проекте. У меня возникла ошибка с отображением карты из-за bootstrap-4. Его классы .container дополнительно накладывается на тот класс что используется в решении (bootstrap устанавливал по этой инструкции https://loiane.com/2017/08/how-to-add-bootstrap-to-an-angular-cli-project/).
Ну и мой вопрос, как быть дальше:
1. Отключать bootstrap (не вариант)?
2. Есть какие-то предложения как мне решить данную проблему?

**Comment by ddubrava** [comment]
Привет!

Заменил .container класс на инлайновые стили, обновись до [1.11.3](https://github.com/ddubrava/angular-yandex-maps/commit/1ba562f6482093d3e632bba49e241adefd340245). Спасибо!

**Comment by frodoom** [comment]
Всё работает. Большое спасибо!
