### ISSUE TITLE
How to change the list of controls

### ISSUE THREAD

**Issue by oleg0032** [ddubrava/angular-yandex-maps#9]
How to set a list of controls that should be displayed on the map?

```
<angular-yandex-map [center]="[55.751952, 37.600739]" [zoom]="12">
    <angular-yandex-placemark [geometry]="[55.751952, 37.600739]"></angular-yandex-placemark>
</angular-yandex-map>
```

Example: https://tech.yandex.ru/maps/jsbox/2.1/customSet_controls

**Comment by ddubrava** [comment]
Привет!

Документация компонента - [Map](https://ddubrava.github.io/angular-yandex-maps-docs/docs/map).

Inputs содержат state & options. Они имеют точно такие же интерфейсы как в документации Яндекс.Карт. Вот нужные [контролы](https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/Map-docpage/#Map__param-state.controls).

Теперь надо в Map передать, используя [state], что написано в документации Яндекс.Карт.

https://stackblitz.com/edit/map-controls
